# Generated by Django 3.1 on 2020-08-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(max_length=10, verbose_name='아이디')),
                ('user_pw', models.TextField(max_length=64, verbose_name='비밀번호')),
                ('user_email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
            ],
        ),
    ]
